# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2314951/Vivado/MicroProcessor/MicroProcessor.cache/wt [current_project]
set_property parent.project_path /home/s2314951/Vivado/MicroProcessor/MicroProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/MouseTransmitter.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/MouseReceiver.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/MouseMasterSM.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Stack.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/TenHz_cnt.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/IRTransmitterSM.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/seg7decoder.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/MouseTransceiver.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/buttonDetecor.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/ALU.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/VGA_Sig_Gen.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Frequency_Divider.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Frame_Buffer.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Timer.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/seg7Driver.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/ROM.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/RAM.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Processor.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Mouse.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/IR.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/Button.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/VGA_Controller.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/LED_Controller.v
  /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/sources_1/new/TOP.v
}
read_xdc /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/constrs_1/new/TOP.xdc
set_property used_in_implementation false [get_files /home/s2314951/Vivado/MicroProcessor/MicroProcessor.srcs/constrs_1/new/TOP.xdc]

synth_design -top TOP -part xc7a35tcpg236-1
write_checkpoint -noxdef TOP.dcp
catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
